<script setup lang="ts">
import { computed } from 'vue';
import { RefreshCw, Save, ShoppingBag } from 'lucide-vue-next';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const props = defineProps<{
    show: boolean;
    mode: 'create' | 'edit';
    form: any; 
    categories: Array<{ id: number; name: string }>;
    locations: Array<{ id: number; name: string }>;
    isSyncing: boolean;
}>();

const emit = defineEmits(['close', 'submit', 'sync']);

// Helper: Calculate Expiry Year in real-time
const expiryYear = computed(() => {
    const purchase = parseInt(props.form.purchase_year);
    const years = parseInt(props.form.period); // Ensure using 'period'
    
    if (!purchase || !years) return null;
    return purchase + years;
});
</script>

<template>
    <Dialog :open="show" @update:open="(val:boolean) => !val && emit('close')">
        <DialogContent class="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
            <DialogHeader>
                <DialogTitle>{{ mode === 'create' ? 'Add New Asset' : 'Edit Asset' }}</DialogTitle>
                <DialogDescription v-if="mode === 'create'">Enter asset details matching physical data or GLPI.</DialogDescription>
            </DialogHeader>
            
            <form @submit.prevent="emit('submit')" class="grid gap-4 py-4">
                
                <div class="grid grid-cols-2 gap-4">
                    <div class="grid gap-2">
                        <Label>Asset Tag</Label>
                        <Input v-model="form.asset_tag" placeholder="Auto-generated" disabled class="bg-muted text-muted-foreground" />
                        <span class="text-[10px] text-muted-foreground">*Automatically generated by the system</span>
                    </div>
                    <div class="grid gap-2">
                        <Label>Serial Number <span class="text-red-500">*</span></Label>
                        <div class="flex gap-2">
                            <Input v-model="form.serial_number" placeholder="SN123456" required class="bg-background" />
                            <Button type="button" variant="outline" size="icon" @click="emit('sync')" 
                                :disabled="isSyncing" title="Sync from GLPI">
                                <RefreshCw class="h-4 w-4" :class="{ 'animate-spin': isSyncing }" />
                            </Button>
                        </div>
                    </div>
                </div>

                <div class="grid gap-2">
                    <Label>Asset Name</Label>
                    <Input v-model="form.name" placeholder="Example: MacBook Pro M3 14 Inch" class="bg-background" />
                </div>

                <div class="grid grid-cols-2 gap-4">
                    <div class="grid gap-2">
                        <Label>Brand</Label>
                        <Input v-model="form.brand" placeholder="Apple" class="bg-background" />
                    </div>
                    <div class="grid gap-2">
                        <Label>Model</Label>
                        <Input v-model="form.model" placeholder="A2991" class="bg-background" />
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4">
                    <div class="grid gap-2">
                        <Label>Category</Label>
                        <Select v-model="form.category_id">
                            <SelectTrigger class="bg-background">
                                <SelectValue placeholder="Select Category" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem v-for="cat in categories" :key="cat.id" :value="String(cat.id)">
                                    {{ cat.name }}
                                </SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                    <div class="grid gap-2">
                        <Label>Initial Location</Label>
                        <Select v-model="form.location_id">
                            <SelectTrigger class="bg-background">
                                <SelectValue placeholder="Select Location" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem v-for="loc in locations" :key="loc.id" :value="String(loc.id)">
                                    {{ loc.name }}
                                </SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                </div>

                <div class="border rounded-md p-3 mt-2 bg-purple-50/50 border-purple-100 dark:bg-purple-900/10 dark:border-purple-800">
                    <div class="flex items-center gap-2 mb-3">
                        <ShoppingBag class="w-4 h-4 text-purple-600 dark:text-purple-400" />
                        <div class="text-xs font-semibold text-purple-700 dark:text-purple-300 uppercase tracking-wider">
                            Procurement Information
                        </div>
                    </div>
                    
                    <div class="grid grid-cols-3 gap-3">
                        <div class="grid gap-1">
                            <Label class="text-xs">Purchase Year</Label>
                            <Input type="number" v-model="form.purchase_year" class="h-9 bg-white dark:bg-background" placeholder="YYYY" />
                        </div>

                        <div class="grid gap-1">
                            <Label class="text-xs">Period (Years)</Label>
                            <div class="relative">
                                <Input type="number" v-model="form.period" class="h-9 bg-white dark:bg-background pr-8" placeholder="0" min="0" />
                                <span class="absolute right-3 top-2.5 text-xs text-muted-foreground">Yrs</span>
                            </div>
                        </div>

                        <div class="grid gap-1">
                            <Label class="text-xs">Vendor</Label>
                            <Input v-model="form.vendor" class="h-9 bg-white dark:bg-background" placeholder="Vendor Name" />
                        </div>
                    </div>

                    <div v-if="expiryYear" class="mt-2 text-[10px] px-2 py-1 rounded inline-block bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300">
                        Valid until year: <strong>{{ expiryYear }}</strong>
                    </div>
                </div>

                <div class="border rounded-md p-3 mt-2 bg-slate-50 border-slate-200 dark:bg-slate-900/30 dark:border-border">
                    <div class="text-xs font-semibold text-muted-foreground mb-3 uppercase tracking-wider">Hardware Specifications</div>
                    <div class="grid grid-cols-2 gap-3">
                        <div class="grid gap-1">
                            <Label class="text-xs">Processor</Label>
                            <Input v-model="form.hardware_specs.cpu" class="h-8 text-xs bg-white dark:bg-background" placeholder="e.g. Intel i5" />
                        </div>
                        <div class="grid gap-1">
                            <Label class="text-xs">RAM</Label>
                            <Input v-model="form.hardware_specs.ram" class="h-8 text-xs bg-white dark:bg-background" placeholder="e.g. 16GB" />
                        </div>
                        <div class="grid gap-1">
                            <Label class="text-xs">Storage</Label>
                            <Input v-model="form.hardware_specs.storage" class="h-8 text-xs bg-white dark:bg-background" placeholder="e.g. 512GB SSD" />
                        </div>
                        <div class="grid gap-1">
                            <Label class="text-xs">OS</Label>
                            <Input v-model="form.hardware_specs.os" class="h-8 text-xs bg-white dark:bg-background" placeholder="e.g. Windows 11" />
                        </div>
                    </div>
                </div>
            </form>

            <DialogFooter>
                <Button variant="outline" @click="emit('close')">Cancel</Button>
                <Button type="submit" @click="emit('submit')" :disabled="form.processing">
                    <Save class="mr-2 h-4 w-4" /> {{ mode === 'create' ? 'Save Data' : 'Update Data' }}
                </Button>
            </DialogFooter>
        </DialogContent>
    </Dialog>
</template>